# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0003_auto_20160418_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='tags',
            field=models.ManyToManyField(blank=True, to='wanted.Tag'),
        ),
    ]
